/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIdentifierRouteImport } from './routes/jobs.$identifier'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdentifierRoute = JobsIdentifierRouteImport.update({
  id: '/jobs/$identifier',
  path: '/jobs/$identifier',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jobs/$identifier': typeof JobsIdentifierRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jobs/$identifier': typeof JobsIdentifierRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jobs/$identifier': typeof JobsIdentifierRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/jobs/$identifier'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/jobs/$identifier'
  id: '__root__' | '/' | '/jobs/$identifier'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JobsIdentifierRoute: typeof JobsIdentifierRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$identifier': {
      id: '/jobs/$identifier'
      path: '/jobs/$identifier'
      fullPath: '/jobs/$identifier'
      preLoaderRoute: typeof JobsIdentifierRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JobsIdentifierRoute: JobsIdentifierRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
